# dependabot.yml file with updates
# disabled for Docker and limited for npm

version: 2
updates:
  # Configuration for npm
  - package-ecosystem: "pip"
    directory: "."
    schedule:
      interval: "daily"
